version: '3'

services:
  db:
    image: postgres:14-alpine
    container_name: db
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 5s
      retries: 5

    env_file:
      - .env
    expose:
      - "5432"

  app:
    build: .
    command: >
      bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"

    ports:
      - '8000:8000'

    depends_on:
      db:
        condition: service_healthy

    env_file:
      - .env



  redis:
    image: redis
#    command: --name some-redis -d redis

    ports:
      - '6379:6379'

    expose:
      - '6379'

    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "localhost", "ping" ]
      interval: 1m
      timeout: 5s

    depends_on:
      - app
      - db

  celery:
    build: .
    command: celery -A config worker -l INFO

    env_file:
      - .env

    depends_on:
      - app
      - redis
      - db

