# Generated by Django 4.2.4 on 2023-09-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('description', models.TextField(max_length=5000, verbose_name='description')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='images/courses/', verbose_name='preview')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('description', models.TextField(max_length=5000, verbose_name='description')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='images/courses/', verbose_name='preview')),
                ('video_url', models.URLField(max_length=400, verbose_name='video_url')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
                'ordering': ('title',),
            },
        ),
    ]
