# Generated by Django 4.2.3 on 2023-09-12 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_subscription_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='course_paid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.course', verbose_name='course paid'),
        ),
    ]
